auction_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),  # Include the auctions app URLs
]

auctions/urls.py
# auctions/urls.py

from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r"^$", views.Home.as_view(), name="home"),
    re_path(r"^login/$", views.LoginView.as_view(), name="login"),
    re_path(r"^signup/$", views.SignUp.as_view(), name="signup"),
    re_path(
        r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.Activate.as_view(),
        name="activate",
    ),
    # path("", views.item_list, name="item_list"),
    path("item/<int:item_id>/", views.item_detail, name="item_detail"),
    re_path(r"^logout/$", views.LogoutView.as_view(), name="logout"),
    re_path(
        r"^profile/(?P<user_id>[0-9]+)/$", views.ProfileView.as_view(), name="profile"
    ),
    re_path(
        r"^profile/(?P<user_id>[0-9]+)/edit/$",
        views.ProfileEdit.as_view(),
        name="edit_profile",
    ),
    re_path("seller/", views.AddProduct.as_view(), name="add_product"),
    re_path(r"^buyer/(?P<p_id>[0-9]+)/$", views.ProductView.as_view(), name="product"),
    re_path(r"^buyer/$", views.BuyerView.as_view(), name="buyer"),
    path("products_listed/", views.ProductListed.as_view(), name="products_listed"),
    path(
        "bids_currently_winning/",
        views.BidsCurrentlyWinning.as_view(),
        name="bids_currently_winning",
    ),
    path("bids_won/", views.BidsWon.as_view(), name="bids_won"),
    re_path(r"^ajax/search/$", views.search, name="search"),
    re_path(r"^ajax/options/$", views.options, name="options"),
    path("rent/", views.RentView.as_view(), name="rent_list"),
    path("rent/<int:pk>/", views.RentProductView.as_view(), name="rent_product"),
    path("products_rented/", views.ProductsRented.as_view(), name="products_rented"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auctions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.validators import MinValueValidator
from django.utils import timezone
import datetime

class AuctionItem(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    starting_bid = models.DecimalField(max_digits=10, decimal_places=2)
    current_bid = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to="auction_images/", blank=True, null=True)
    end_date = models.DateTimeField()
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="items")


class Bid(models.Model):
    item = models.ForeignKey(AuctionItem, on_delete=models.CASCADE, related_name="bids")
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)


class MyProfile(models.Model):

    CHOICE_SET1 = (("Male", "Male"), ("Female", "Female"), ("Others", "Others"))

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(max_length=10, null=True, blank=True)
    avatar = models.ImageField(upload_to="profile_pic", default="profile.png")
    gender = models.CharField(max_length=10, choices=CHOICE_SET1, default="Male")

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_MyProfile(sender, instance, created, **kwargs):
        if created:
            MyProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_MyProfile(sender, instance, **kwargs):
        instance.myprofile.save()


class Product(models.Model):
    CHOICE = (
        ("Grocery", "Grocery"),
        ("Mobiles", "Mobiles"),
        ("Clothes", "Clothes"),
        ("Electronics", "Electronics"),
        ("Home Appliances", "Home appliances"),
        ("Beauty", "Beauty"),
        ("Toys", "Toys"),
        ("Sports", "Sports"),
        ("Footwear", "Footwear"),
        ("Others", "Others"),
    )
    option = (("Sell", "Sell"), ("Rent", "Rent"))
    seller_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=False,
        related_name="%(class)s_seller",
    )
    name = models.CharField(max_length=50, blank=False, unique=True)
    desp = models.TextField(max_length=500, blank=False, null=True)
    category = models.CharField(max_length=50, blank=True, null=True, choices=CHOICE)
    minimum_price = models.IntegerField(
        blank=True, validators=[MinValueValidator(1)], default=1
    )
    start = models.DateTimeField(default=timezone.now, null=True)
    end = models.DateTimeField(default=timezone.now() + timezone.timedelta(hours=10))
    current_bid = models.IntegerField(default=0)
    product_sold = models.BooleanField(default=False)
    choose = models.CharField(max_length=50, blank=True, null=True, choices=option)
    bidder_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="%(class)s_bidder",
    )
    rent_status = models.BooleanField(default=False)
    rent_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="%(class)s_rent",
    )
    rent_price = models.IntegerField(default=0)
    rent_time_start = models.DateTimeField(null=True)
    rent_time_end = models.DateTimeField(null=True)
    rent_fine = models.IntegerField(default=0)
    # bid_only = models.BooleanField(default=False)
    # rent_only = models.BooleanField(default=False)
    # rent_and_bid = models.BooleanField(default=True)

    def __str__(self):
        return str(self.id)

auctions/forms.py
from django.core.files.images import get_image_dimensions
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import MyProfile, Product
from django.core.validators import MinValueValidator


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=50, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('This email address is already in use.')

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {
                "class": "form-control",
                "maxlength": "150",
                "placeholder": "Username",
                "autofocus": True,
                "required": True,
                "style": "font-size:130%; padding:5% 3% 5% 3%;",
            }
        )
        self.fields["email"].widget.attrs.update(
            {
                "class": "form-control",
                "maxlength": "50",
                "placeholder": "Email",
                "required": True,
                "style": "font-size:130%; padding:5% 3% 5% 3%;",
            }
        )
        self.fields["password1"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Password",
                "required": True,
                "style": "font-size:130%; padding:5% 3% 5% 3%;",
            }
        )
        self.fields["password2"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Confirm Password",
                "required": True,
                "style": "font-size:130%; padding:5% 3% 5% 3%;",
            }
        )


class EditProfileForm(forms.ModelForm):

    class Meta:
        model = MyProfile
        fields = ('avatar', 'first_name', 'last_name', 'gender', 'date_of_birth', 'phone_number')


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password')


class BidsForm(forms.Form):

    bidder_amount = forms.IntegerField(validators=[MinValueValidator(1)])

    class Meta:
        fields = ('bidder_amount',)


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'desp', 'category', 'minimum_price','rent_price',)

auctions/templates/auctions/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>alx</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>

     <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
         rel = "stylesheet">
    <link rel="stylesheet" href="{% static '/css/main1.css' %}">
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>


<body style="background:rgb(210, 229, 247)">
<script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
<script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

<nav class="navbar navbar-inverse" style="background:rgba(5, 38, 99, 0.678);border:none">
  <div class="container-fluid navelements">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= "{% url 'home' %}">ALX</a>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'profile' user.id %}" style="color:rgb(3, 3, 3)" ><span class="glyphicon glyphicon-user"></span> PROFILE</a></li>
        <li><a href="{% url 'logout' %}" style="color:rgb(3, 3, 3)" ><span class="glyphicon glyphicon-log-in"></span> LOGOUT</a></li>
      </ul>
    </div>
  </div>
</nav>

<nav class="navbar navbar-default" style="margin-top:-1.5%;background:rgb(186, 220, 248);border: none">
        <div class="container " style="font-size:130%" >
          <ul class="nav navbar-nav">
            <li class="nav1"><a href="{% url 'buyer' %}" style="color:rgb(3, 3, 3)" >Buyer Section</a></li>
            <li class="nav1"><a href="{% url 'bids_won' %}" style="color:rgb(3, 3, 3)" >Bids Won</a></li>
            <li class="nav1"><a href="{% url 'bids_currently_winning' %}" style="color:rgb(3, 3, 3)"  >Bids Curently Winning </a></li>
            <li class="nav1"><a href="{% url 'rent_list' %}" style="color:rgb(3, 3, 3)">Rent Section</a></li>
            <li class="nav1"><a href="{% url 'products_rented' %}" style="color:rgb(3, 3, 3)">Products Rented</a></li>
            <li class="nav1"><a href="{% url 'products_listed' %}" style="color:rgb(3, 3, 3)" >Seller Section</a></li>
          </ul>
        </div>
      </nav>


{% block home %}

{% endblock %}


{% block bids_currently_winning  %}

{% endblock %}


{% block bids_won %}

{% endblock %}


{% block buyer %}

{% endblock %}


{% block cannot_bid %}

{% endblock %}


{% block edit_profile %}

{% endblock %}


{% block product_form %}

{% endblock %}


{% block product_listed %}

{% endblock %}


{% block product_sold %}

{% endblock %}


{% block bidding %}

{% endblock %}


{% block profile %}

{% endblock %}

{% block rent_list %}

{% endblock %}


{% block rent_product %}

{% endblock %}


{% block product_already_rented %}

{% endblock %}

{% block products_rented %}

{% endblock %}


{% block javascript %}

{% endblock %}


</body>
</html>

auctions/templates/auctions/bids_currently_winning.html
{% extends 'auctions/base1.html' %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block bids_currently_winning %}
{% if product %}
<h1 style="margin-bottom:40px; margin-left:35%; font-size:35px; color:white; font-weight:bold;">BIDS CURRENTLY RUNNING</h1>
<div style="text-align:left; ">
<table class="table tb box-shadow--6dp">
    <thead>
    <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Current Bid</th>
        <th>Seller Username</th>
    </tr>
    </thead>


{% for p in product %}
    <tbody>
    <tr>
        <td>{{p.name}}</td>
        <td >{{ p.category }}</td>
        <td >{{ p.current_bid }}</td>
        <td >{{ p.seller_id}}</td>
    </tr>
    </tbody>

{% endfor %}
</table>
{% else %}
    <br>
    <h1 style="text-align:center; color: white; font-size:30px; padding:10px;">YOU ARE NOT WINNING!!!!</h1>
 {% endif %}
</div>

{% endblock %}
</body>

</html>

auctions/templates/auctions/bids_won.html
{% extends 'auctions/base1.html' %}
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block bids_won %}
{% if product %}


<h1 style="margin-bottom:40px; margin-left:42%; font-size:35px; color:white; font-weight:bold;">BIDS WON</h1>
<div style="text-align:center;  margin-left:23%;margin-right:10%;">
<table class="table tb box-shadow--6dp">
    <thead>
    <tr>
        <th style="font-size:28px; padding:10px;">Name</th>
        <th style="font-size:28px; padding:10px;">Category</th>
        <th style="font-size:28px; padding:10px;">Highest Bid</th>
        <th style="font-size:28px; padding:10px;">Seller Username</th>
    </tr>
    </thead>
{% for p in product %}
    <tbody>
    <tr>
        <td style="font-size:30px; padding:10px;">{{p.name}}</td>
        <td style="font-size:30px; padding:10px;">{{ p.category }}</td>
        <td style="font-size:30px; padding:10px;">{{ p.current_bid }}</td>
        <td style="font-size:30px; padding:10px;">{{ p.seller_id}}</td>
    </tr>
    </tbody>

{% endfor %}
</table>
{% else %}
    <br>
    <h1 style="text-align:center; color: white; font-size:30px; padding:10px;">YOU HAVE NOT WON ANY BID!!!!</h1>
 {% endif %}
</div>
{% endblock %}
</body>
</html>

auctions/templates/auctions/buyer.html
{% extends 'auctions/base1.html' %}
{% load static %}

{% block buyer %}

{% if product_list %}
<form method="post" style="margin-left:2vw; margin-top:-1vw;  color:black;  position:absolute;">
    <br>
    <br>
    <h1 style="color:white; font-size:20px; font-family:cursive">SORT-BY:-</h1>
    {% csrf_token %}
    <br>

    <button class="sort1" type="submit" value="new_to_old" name="sort" style="cursor: pointer;  margin:6px; border-radius:10px;"> NEW TO OLD   </button>
    <br>
    <button class="sort2" type="submit" value ="old_to_new" name="sort" style="cursor: pointer;  margin:6px; border-radius:15px;"> OLD TO NEW  </button>
    <br>
    <button class="sort3" type="submit" value="high_to_low" name="sort" style="cursor: pointer;  margin:6px; border-radius:15px;"> HIGH TO LOW </button>
    <br>
    <button class="sort4" type="submit" value ="low_to_high" name="sort" style="cursor: pointer;  margin:6px; border-radius:15px;"> LOW TO HIGH </button>
     <br>
    <button class="sort5" type="submit" value ="unsold" name="sort" style="cursor: pointer; margin:6px; border-radius:15px;"> UNSOLD ITEMS</button>

</form>

    {% for product in product_list %}
      <ul class="product-list" style="font-size:10px;">
          <li>
          <h1><a href="{% url 'product' p_id=product.pk %}" style="text-decoration:none;">{{ product.name }}</a></h1>
              <h2 style="font-size:20px;" ><b>Start Time:-{{product.start}}</b></h2>
              <h2 style="font-size:20px;"><b>End Time:-{{product.end}}</b></h2>
              <h2 style="font-size:20px;"><b>Current Bid:-{{product.current_bid}}</b></h2>
          </li>
    <br>
    </ul>

    {% endfor %}

{% else %}
<br>
    <p style="color:white; font-size:30px; margin-left:40%;">NO BIDS ARE AVAILABLE</p>
{% endif %}
{% endblock %}

auctions/templates/auctions/edit_profile.html
{% extends 'auctions/base1.html' %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
{% block edit_profile %}
<form method="post" enctype="multipart/form-data" class="tk box-shadow--6dp ">

    <h1 class="display-1" style="text-align:center;">EDIT PROFILE</h1>


    {% csrf_token %}

    <h2 class="prof">UserName : {{user.username }}</h2>
    <h2 class="prof">Email:  {{ user.email }}</h2>



    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
    <p style="color: red;">{{ error }}</p>
    {% endfor %}
    </p>

    {% endfor %}<br>
    <button type="submit" style="margin-left:50%;">Save</button>

</form>

{% endblock %}
</body>
</html>

auctions/templates/auctions/home1.html
{% extends 'auctions/base1.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block javascript %}
   <script >
  $("#value").click(function () {
        console.log("1");

      $.ajax({


        url: "{% url 'search' %}",

        data: {

          'value1':$('#value1').val()
        },
        dataType: 'json',
        success: function (data) {

        var res="";
        var products = data['products'];

        if(products.length!=0)
        {

         res="<ul>";
            for(var i = 0; i < products.length; i++ ){
                 console.log(products[i][0]);
                 res += "<li> <a href=\"../auctions/buyer/" + products[i][1] + "\">" +  products[i][0] + "</a></li>";

            }
            res += "</ul>";}
            else
            res="<div><br><br>No results</div>"



            $("#results").html(res);
          }

      });


    });
$(function(){
            console.log("67");

            var t = [
               "mobiles",
               "grocery",
               "clothes",
               "electronics",
               "home appliances",
               "beauty",
               "toys",
               "sports",
               "footwear",
               "others"

            ];




            $( "#value1" ).autocomplete({
               minLength:1,
               delay:500,
               source:function(req,add){
               var search=$("#value1").val();
               $.ajax({
               url:"{% url 'options' %}",
               async:false,
               dataType:'json',
               type:'GET',
               data:{'value1':search,},
               success:function(data){
               var suggestions=[];
               $.each(data,function(index,objeto){
               suggestions.push(objeto);
               });
               add(suggestions);

               },
               error:function(err){
               alert("error");
               }
               });
               }

            });
         });

  </script>
{% endblock %}
{% block home %}
<div id="myCarousel" class="carousel slide" data-ride="carousel" style="max-height:400px;" >
            <!-- Indicators
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol> -->

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <img src="{% static '/images/c2.jpg' %}" alt="Los Angeles" style="width:100%;max-height:400px;" >
              </div>

              <div class="item">
                <img src="{% static '/images/c3.jpg' %}" alt="Chicago" style="width:100%;max-height:400px;">
              </div>

              <div class="item">
                <img src="{% static '/images/c4.jpg' %}" alt="New york" style="width:100%;max-height:400px;">
              </div>
            </<div>



            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>


          <div class="main-text">
                <div class="col-md-12 text-center">
                    <h1><b>
                        WELCOME TO ALX</b></h1>
                    <h3>
                        SELL, BUY USING AUCTION AND RENT!!!
                    </h3>
                    <div class="input-group sr">
                            <input class="form-control srip" type="text" id="value1"  placeholder="Search" aria-label="Search">
                            <div class="input-group-btn">
                                <button class="btn btn-default" id="value" type="submit">
                                    <i class="glyphicon glyphicon-search srip"></i> </button>
                      </div>
                    </div>
                </div>
            </div>


                   <div class="card bg-primary srcard">

              <div class="card-body text-center" id="results" style="background-color:lightblue;">


              </div>
                </div>


{% endblock %}
</body>
</html>

auctions/templates/auctions/product.html
{% extends 'auctions/base1.html' %}
{% load static %}

{% block bidding %}

<div style="text-align:center; font-size:20px; margin-top:40px; font-weight:bold; font-family:sans-serif;">


   <h2>Name:- {{ name }}</h2>
   <br>


   <h4>DESCRIPTION:-{{ desp}}</h4>


   <br>
   <h4>CATEGORY:-{{ category}}</h4>
   <br>

   <h4>MINIMUM BID:-{{ minbid}}</h4>
   <br>

   <h4>BID START :-{{ start}}</h4>
   <br>

   <h4>BID END:-{{ end}}</h4>
   <br>

   <h4 id="bid_value">{{ currentbid }}</h4>
<br>

<form id="form_data" method="post">

    {% csrf_token %}

    <label>{{ form.as_p }}

    </label>
    <br>
    <input type="submit" value="SUBMIT">

</form>
</div>
<script>
    var loc = window.location;
    var wsStart = 'ws://';
    var endpoint = wsStart + loc.host + loc.pathname;
    var socket = new ReconnectingWebSocket(endpoint);

    var form_data = $('#form_data');
    var bid_input = $('#id_bidder_amount');
    var bid_holder = $('#bid_value');

    socket.onmessage = function(e){
        console.log("message", e)
        bid_holder.html(e.data);
    }

    socket.onopen = function(e){
        console.log("open", e)

        form_data.submit(function(event){
            event.preventDefault()
            var bid_value = bid_input.val();
            bid_input.val('')
            console.log(bid_value)
            var final_data = {
                'bid': bid_value
            };
            socket.send(JSON.stringify(final_data))
        })
    }

    socket.onerror = function(e){
        console.log("error", e)
    }

    socket.onclose = function(e){
        console.log("close", e)
    }
</script>
{% endblock %}

auctions/templates/auctions/product_form.html
{% extends 'auctions/base1.html' %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-image: url('back.jpg');background-size: cover;">


{% block product_form %}



        <form method="POST" class="tm box-shadow--6dp" enctype="multipart/form-data">
        {% csrf_token %}
         <h1 class="display-1">ADD PRODUCT</h1>
        <div class="form-group">
        <label  class="lbsz">Name:</label>
        <input type="text" class="form-control sz" name="name" maxlength="50" required="" id="id_name" placeholder="Name">
        </div>
        <div class="form-group">
        <label  class="lbsz">Description:</label>
        <textarea name="desp" cols="30" class="form-control sz" rows="5" maxlength="100" required="" id="id_desp" placeholder="Description"></textarea>
        </div>
            <div class="form-group">
        <label class="lbsz">Category:</label>
        <select name="category" id="id_category" class="form-control sz">
  <option value="" selected>---------</option>

  <option value="Grocery">Grocery</option>

  <option value="Mobiles">Mobiles</option>

  <option value="Clothes">Clothes</option>

  <option value="Electronics">Electronics</option>

  <option value="Home Appliances">Home Appliances</option>

  <option value="Beauty">Beauty</option>

  <option value="Toys">Toys</option>

  <option value="Sports">Sports</option>

  <option value="Footwear">Footwear</option>

  <option value="Others">Others</option>

</select>
            </div>
  <div class="form-group">
  <label for="id_minimum_price" class="lbsz">Minimum price:</label>
<input type="number" name="minimum_price" value="1" id="id_minimum_price" class="form-control sz">
  </div>
 <div class="form-group">
<label for="rent_price" class="lbsz">Rent price</label>
            <input type="number" name="rent_price" id="rent_price" class="form-control sz">
 </div>

 <div class="form-group row ">
            <div class="col-sm-10">
<button type="submit" class="btn btn-primary" style="font-size:80%;">Save</button>
 </div>
          </div>

</form>
{% endblock %}

</body>
</html>

auctions/templates/auctions/product_listed.html
{% extends 'auctions/base.html' %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>

    </style>
</head>
<body>
{% block product_listed %}
{% if product %}

<h1 style="margin-bottom:40px; margin-left:40%; font-size:35px; color:white; font-weight:bold;">PRODUCTS LISTED</h1>
<div style="text-align:center;  margin-left:30%;">
<table>
    <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Current Bid</th>
        <th>Bidder Name</th>
        <th>Sold Status</th>
    </tr>

{% for p in product %}
    <tr>
        <td>{{p.name}}</td>
        <td>{{ p.category }}</td>
        <td>{{ p.current_bid }}</td>
        <td>{{ p.bidder_id}}</td>
        <td>{{ p.product_sold}}</td>
    </tr>
{% endfor %}
</table>
    <br>
     <a class="sell-more" href="{% url 'add_product'%}" style="text-decoration:none;  margin-left:-40% ; "> SELL MORE PRODUCT </a>
{% else %}
    <br>
    <h1 style="text-align:center; font-size:30px; color:white;">YOU HAVE NOT LISTED ANY PRODUCT FOR BIDDING</h1>
    <br>
    <br>
    <br>
    <a class="sell-product" href="{% url 'add_product'%}" style="text-decoration:none; margin-left:45%; margin-top:5%;">SELL PRODUCTS</a>
 {% endif %}
</div>
{% endblock %}
</body>
</html>